version: '3.8'
services:
  www-api:
    image: ubuntu/apache2:latest
    container_name: www-api
    ports:
      - "80:80"
    networks:
      - api-network
  db-api:
    image: postgres:14-alpine
    container_name: db-api
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    networks:
      - api-network
networks:
  api-network:
    driver: bridge